### ISSUE TITLE
Alpine 3.19.0: vulnerabilities in OpenSSL

### ISSUE THREAD

**Issue by sjinks** [Automattic/vip-container-images#618]
Reported by Trivy:

| Package | Vulnerability ID | Severity | Installed Version | Fixed Version | Links |
| ------- | ---------------- | :------: | ----------------- | ------------- | ----- |
| libcrypto3 | CVE-2023-6129 | MEDIUM | 3.1.4-r2 | 3.1.4-r3 | https://avd.aquasec.com/nvd/cve-2023-6129 |
| libcrypto3 | CVE-2023-6237 | MEDIUM | 3.1.4-r2 | 3.1.4-r4 | https://avd.aquasec.com/nvd/cve-2023-6237 |
| libssl3 | CVE-2023-6129 | MEDIUM | 3.1.4-r2 | 3.1.4-r3 | https://avd.aquasec.com/nvd/cve-2023-6129 |
| libssl3 | CVE-2023-6237 | MEDIUM | 3.1.4-r2 | 3.1.4-r4 | https://avd.aquasec.com/nvd/cve-2023-6237 |

Related issues:
- [x] https://github.com/Automattic/vip-container-images/security/code-scanning/9645
- [x] https://github.com/Automattic/vip-container-images/security/code-scanning/9646
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/vip-container-images/pull/619
- [ ] https://github.com/Automattic/vip-container-images/pull/621
- [ ] https://github.com/Automattic/vip-container-images/pull/620
- [ ] https://github.com/Automattic/vip-container-images/pull/622
```

**Comment by sjinks** [comment]
Alpine image [has been rebuilt](https://github.com/Automattic/vip-container-images/actions/runs/7569039498/job/20611489030#step:4:981)

```
ghcr.io/automattic/vip-container-images/alpine:3.19.0 (alpine 3.19.0)
=====================================================================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```

**Comment by sjinks** [comment]
- [ ] https://github.com/Automattic/vip-container-images/security/code-scanning/9645
- [ ] https://github.com/Automattic/vip-container-images/security/code-scanning/9646
